name: Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
permissions:
        contents: write
        pages: write
        id-token: write
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose   

    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.yml build

    - name: Run tests
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh